### ISSUE TITLE
Compiler error after installation

### ISSUE THREAD

**Issue by baffalop** [benfaerber/rescript-react-router-dom#1]
I'm quite new to ReScript so apologies if this is my mistake. After running `pnpm i react-router-dom rescript-react-router-dom` and adding the statement `open RescriptReactRouterDom.ReactRouterDOM`, I get this error from the compiler:

```
Dependency on rescript-react-router-dom
rescript: [1/1] src/ReactRouterDOM-RescriptReactRouterDom.cmj
FAILED: src/ReactRouterDOM-RescriptReactRouterDom.cmj

  We've found a bug for you!
  my-project/.pnpm/rescript-react-router-dom@1.0.6/node_modules/rescript-react-router-dom/src/ReactRouterDOM.res:5:22-27

  3 │   search: string,
  4 │   hash: string,
  5 │   state: option<Js.t<string>>,
  6 │   key: string
  7 │ }

  This type string should be an instance of type {..}
```

I'm not familiar with what `type {..}` means, but I guess this can only come from some internal type mismatch within the bindings?

**Comment by benfaerber** [comment]
Hi! Thanks for trying out the library. The problem is the Js.t constructor. The newest version of rescript deprecated it so now we can just use normal strings. Version 1.0.8 now has the fix. (I was on my computer already enjoy the quick fix haha)

If you need any help with rescript feel free to send me a message: faerberbendev@protonmail.com!

**Comment by baffalop** [comment]
That _was_ quick! Thanks, seems to be working!
